// ZALAVAD PATIDAR BUSINESS DIRECTORY DATA

var directoryData = [
  {
    fullName: "VARMORA JIGAR MANHARBHAI",
    whatsapp: "9409490194",
    village: "SARA",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "BHIMANI INTERNATIONAL LLP",
    businessType: "EXPORT",
    email: "",
    website: "",
    address: "MAHENDRANAGAR CHOKDI",
    visitingCard: ""
  },
  {
    fullName: "Kachrola Prakash keshavjibhai",
    whatsapp: "9825829695",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Varmora Group",
    businessType: "Ceramic tiles and Bathware",
    email: "prakashpatel@varmora.com",
    website: "www.varmora.com",
    address: "Varmora Grainito pvt.ltdAt-Dhuva .NH8A wankaner morbi Highway",
    visitingCard: ""
  },
  {
    fullName: "Sanghani Rajesh Rameshbhai ",
    whatsapp: "8264982473",
    village: "Danawada",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Pramukh electronics & Alexa International ",
    businessType: "Electronics & tiles ",
    email: "rajeshsanghani421@gmail.com",
    website: "",
    address: "RR8C+82W, Moonnagar Street Number 4, Rajnagar, Sardar Nagar, Morbi, Gujarat 363641",
    visitingCard: ""
  },
  {
    fullName: "Rakesh Kumar Gangaram bhai kunpara ",
    whatsapp: "9638439321",
    village: "Chamaraj ",
    taluka: "Wadhwan",
    bloodGroup: "O+",
    businessName: "Maruti electric and inverter service ",
    businessType: "Electric ",
    email: "rp3032734@gmail.com ",
    website: "",
    address: "Nani kenal road  sanraiz vila shop no 110",
    visitingCard: "https://drive.google.com/open?id=19z-WH5ahVxRh6gSIH8tjbseGk6pyHm02"
  },
  {
    fullName: "MAKASANA DHAVAL PARBHUBHAI",
    whatsapp: "7990849787",
    village: "Moti malvan",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Clone ceramic",
    businessType: "Tiles teding and cuting ",
    email: "",
    website: "",
    address: "Halvad rode .hariom park. Mahendarnagar ",
    visitingCard: "https://drive.google.com/open?id=1bwEszAMHPYzThC871lQBDhE1MSwyZE7M"
  },
  {
    fullName: "Gopani Prayag Ashok bhai",
    whatsapp: "7984776859",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Digital Diva",
    businessType: "Digital Marketing Services",
    email: "prayaggopani29@gmail.com",
    website: "www.digital-diva.com",
    address: "S-6, 2nd Floor, Shiv Plaza, Nani canal Road, Opp. Kishan Park, Panchasar Road, Morbi.",
    visitingCard: "https://drive.google.com/open?id=1OydA9qyl-p7hlsd-9J58B4C3qou02uFj"
  },
  {
    fullName: "Kavar montu ranchhodbhai",
    whatsapp: "9428718254",
    village: "Khodu",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Patidar impex & solution",
    businessType: "Barcode labels , sticker",
    email: "Montukavar@gmail.com",
    website: "",
    address: "Manendranagar, morbi",
    visitingCard: ""
  },
  {
    fullName: "Vidja Nilesh bhai jasmatbhai",
    whatsapp: "9737803202",
    village: "Mangadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Krometi pepar",
    businessType: "Pepar",
    email: "nilesh3202@gmail.com",
    website: "",
    address: "Halvad rod ",
    visitingCard: "https://drive.google.com/open?id=1gX9Uk-CXY-61ieN0NIw8tvGFqVSpw2xd"
  },
  {
    fullName: "VARMORA BHAGVANJIBHAI MANJI BHAI ",
    whatsapp: "9879993920",
    village: "SARA",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "CHI FASTENERS ",
    businessType: "TREADING NUT BOLT ALL TYPE",
    email: "chi.fasteners@gmail.com",
    website: "",
    address: "C-5 HARI CHEMBERS TRAJPAR CHAR RASTA MORBI GUJARAT 363642",
    visitingCard: "https://drive.google.com/open?id=1RyI-uLizwMAzAC07D_HzQVLmumYm7QaE"
  },
  {
    fullName: "Koladara bhavesh karsan bhai",
    whatsapp: "9638496987",
    village: "Nana ankevadiya",
    taluka: "Lakhtar",
    bloodGroup: "O+",
    businessName: "Shiv shakti enterprises/ trding",
    businessType: "Conveyor belt/ ind.Oil/grese",
    email: "bhaveshkoladara1987@gmail.com",
    website: "",
    address: "Pinak chembur riyal plaza ni same lalpar",
    visitingCard: ""
  },
  {
    fullName: "Mitul kantilal patel",
    whatsapp: "9913561816",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Paper mill ",
    businessType: "Manufacturers ",
    email: "2.opaperproduct@gmail.com ",
    website: "",
    address: "Aniyari,jetpar",
    visitingCard: ""
  },
  {
    fullName: "Jivani ashish janakbhai",
    whatsapp: "9687094549",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Jog ceramic ",
    businessType: "Ceramic sanitaryware trading ",
    email: "ajj2711@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Jivani Dhaval Janakbhai",
    whatsapp: "9904994446",
    village: "Dhrangadhra ",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Rotto Bathware ",
    businessType: "Sanitaryware Wholesaler ",
    email: "dhaval2jivani@gmail.com",
    website: "",
    address: "Rotto Bathware, B/H Maruti Suzuki Workshop, Opp. Pipli Village, Jetpar-Pipli Road, Morbi-2",
    visitingCard: "https://drive.google.com/open?id=1EpYnr1ZsAQ5zO5d7yDzPP47JGM4vzpu5"
  },
  {
    fullName: "DHARMENDRA P BHADJA",
    whatsapp: "8866323222",
    village: "Merupar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "ROTTO TILES ",
    businessType: "ceramic ",
    email: "dpbhadja@gmail.com",
    website: "ROTTO tiles.com ",
    address: "LALPER 8A NATIONAL HIWAY",
    visitingCard: "https://drive.google.com/open?id=1D5MLOFRYXUERDtho1cpN3WeYUGEa9ref"
  },
  {
    fullName: "Rajnikant Mansukhbhai Jagodana",
    whatsapp: "9016316393",
    village: "Thala",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Swastik Plastic & Royal Polyplast LLP",
    businessType: "Reprocess Plastic And Plastic Chair and Furniture",
    email: "rajni.jagodana@gmail.com",
    website: "www.royalpolyplastllp.com",
    address: "27-National Highway, Ravapar Nadi Road, Near Sarvoday Hotel, Morbi - 363642, Gujarat, INDIA.",
    visitingCard: ""
  },
  {
    fullName: "Marvaniya vraj rohit bhai ",
    whatsapp: "8780037637",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Bhimani international llp",
    businessType: "Import export ",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Patel Rupesh Lakshmanbhai",
    whatsapp: "9998910340",
    village: "Methan",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Professor ",
    businessType: "Government job ",
    email: "rlp131277@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Varmora Rahul Kumar Harjivan Bhai",
    whatsapp: "8460032370",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "William John's Pizza Mahendra Nagar ",
    businessType: "Food",
    email: "rahulvarmora@gmail.com",
    website: "",
    address: "Mh",
    visitingCard: ""
  },
  {
    fullName: "Varmora bhailal bhai lakhman bhai ",
    whatsapp: "9925954804",
    village: "Ghutu ",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Gurukrupa enterprise and tiles cuttings ",
    businessType: "Tiles cutting and selling ",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Harjivan Bhai C Varmora",
    whatsapp: "8460032370",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Shree Umiya Novelty Parotha House ",
    businessType: "Food Restaurant ",
    email: "rahulvarmora@gmail.com",
    website: "",
    address: "Citi point complex near Mahendranagar morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Patel hitesh chamanbhai",
    whatsapp: "9726801525",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Linum ceramic ",
    businessType: "Construction ",
    email: "karmkrushi@gmail.com",
    website: "",
    address: "Morbj",
    visitingCard: ""
  },
  {
    fullName: "AERVADIYA LALIT BHANJIBHAI ",
    whatsapp: "9726421212",
    village: "Mangadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "IMPERA CERAMIC ",
    businessType: "WALL TILES MANUFACTURER ",
    email: "lalit@imperaceramic.com",
    website: "www.imperaceramic.com",
    address: "AT. RANGPAR, JETPAR ROAD, MORBI",
    visitingCard: "https://drive.google.com/open?id=1WVGo3v12IU5WmVa1pplnCzj3W-WN4yt2"
  },
  {
    fullName: "Varmora Jay Bharatbhai",
    whatsapp: "9824209436",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "",
    businessName: "Jabaco Overseas LLP",
    businessType: "Export Business ",
    email: "jayvarmora5357@gmail.com",
    website: "www.jabaco.in",
    address: "Shivalik Complex, Mahendranagar Circle, Morbi-363642",
    visitingCard: ""
  },
  {
    fullName: "KAILA HARSHADKUMAR AMBARAMBHAI ",
    whatsapp: "9825296990",
    village: "Ishwarnagar",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Simola tiles",
    businessType: "Marketing ",
    email: "harshadkaila.80@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "BHOJANI SANJAYBHAI MANSUKHBHAI ",
    whatsapp: "9924581646",
    village: "TIKAR",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "VEDANT SCHOOL MORBI",
    businessType: "SCHOOL ",
    email: "sanjaybhojani7301@gmail.com",
    website: "",
    address: "VAVADI MORBI",
    visitingCard: ""
  },
  {
    fullName: "Satapara Jignesh Chamanbhai",
    whatsapp: "7359715147",
    village: "Surendranagar",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Universal Solution ",
    businessType: "Coal, Soda Ash, Marble Powder, Fastners ",
    email: "jignesh.universalmaterial@gmail.com",
    website: "",
    address: "Empire 36, Op Fern Residency, Mahendra Nagar, Morbi-2",
    visitingCard: ""
  },
  {
    fullName: "Makasna vijedrbhai amarsibhai",
    whatsapp: "9687278393",
    village: "Nava devaliya",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Construction ",
    businessType: "Building contractors ",
    email: "",
    website: "",
    address: "Halvad, morbi",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya Mahesh Chhagan Bhai",
    whatsapp: "9909111554",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Khavadiya Trending co.",
    businessType: "Anaj Kariyana",
    email: "",
    website: "",
    address: "A27, Marketing Yard Morbi.",
    visitingCard: ""
  },
  {
    fullName: "DHANJIBHAI VALJIBHAI  DALSANIYA",
    whatsapp: "9825796210",
    village: "Ishwarnagar",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "ORYN MINCHEM",
    businessType: "Bopp tape Roll",
    email: "Preetdalsaniya@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: ""
  },
  {
    fullName: "DETROJA RAJESHKUMAR KALUBHAI",
    whatsapp: "9913720609",
    village: "VANKIYA",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "SHUBHLAXMI CRANOTECH LLP ",
    businessType: "EOT CRANE MANUFACTURER,  INDUSTRIAL CRANE MANUFACTURE ALL TYPE OF FABRICATION WORK",
    email: "Shubhlaxmicranotechllp@gmail.com",
    website: "Www.shubhlaxmicranes.com",
    address: "Survey no - 345/-2, Dhareshwar Mahadev temple Road, Morbi - Halvad High way , At Andarana, Morbi, Gujrat - 363642",
    visitingCard: "https://drive.google.com/open?id=1_TP_z7S26m_REyE7xODMLvIzOc4mMPuW"
  },
  {
    fullName: "Law pareshkumar Jayantilal",
    whatsapp: "9998327972",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Florice polychem LLP",
    businessType: "ceramic Binder",
    email: "floricepolychem@gmail.com",
    website: "",
    address: "Rajkot kandla bypass, Swaminarayan Gurakul Road,Dharmpur road",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya sandip muljibhai",
    whatsapp: "9725555594",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "P.d.patel & sans",
    businessType: "All commodities sels & parches ",
    email: "",
    website: "",
    address: "A31 Marketing yard sanala road",
    visitingCard: "https://drive.google.com/open?id=1ip4AWMtQE1XjiEjpvWO0esQUDM6GPI9k, https://drive.google.com/open?id=16tLp6ScThRJ1OyKlvrIbuEIlXPFWAAUv"
  },
  {
    fullName: "Viramgama harshad bhai daya bhai",
    whatsapp: "9328765988",
    village: "Moti malvan",
    taluka: "Dhrangdhra",
    bloodGroup: "B-",
    businessName: "Bajrang aluminium seksan",
    businessType: "Aelyumimiyam seksan",
    email: "",
    website: "",
    address: "Mahendra nagar chokdi hadvad rod prabhat chebar ",
    visitingCard: ""
  },
  {
    fullName: "Chhatrola Jaykumar Manaharlal",
    whatsapp: "9998458317",
    village: "Limbadi",
    taluka: "LIMBADI",
    bloodGroup: "B+",
    businessName: "Deputy engineer, GETCO",
    businessType: "Goverment Job",
    email: "alwaysjaypatelelec@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Sersiya Ashvin cunilal",
    whatsapp: "9909068121",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Kesri hotal",
    businessType: "Fud",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "KASODIYA YOGESH THAKARSHIBHAI",
    whatsapp: "9737146900",
    village: "Soladi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "KP LABEL ",
    businessType: "ALL TYPES OF  LABEL ",
    email: "kasodiyayogesh8@gmail.com",
    website: "Not available ",
    address: "Uma residency, near by ITI, Ghuntu Road.",
    visitingCard: "https://drive.google.com/open?id=1-gpZSwg9uk8k_r3pMWPpwrb4BiEMHh21"
  },
  {
    fullName: "VARMORA KALPESH",
    whatsapp: "8758711311",
    village: "RANMALPUR",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "BHAGWATI BEST CHEMICALS",
    businessType: "NANO CHEMICAL",
    email: "kalpesh9978940721@gmail.com",
    website: "",
    address: "Mahendranagar, morbi",
    visitingCard: ""
  },
  {
    fullName: "HARSH PATEL",
    whatsapp: "8530402322",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "GENESIS ENTERPRISE",
    businessType: "CHEMICAL & TILES TRADING ",
    email: "genesisenterprisee@gmail.com",
    website: "",
    address: "S-12,Hemratna Chember,Nr.Trajpar Chowkdi,8-A National Highway,Morbi-363641 Gujarat, India",
    visitingCard: "https://drive.google.com/open?id=1GBAx_BccOC3aKl9EEML1n3pzjna9WNlC"
  },
  {
    fullName: "Araniya alpesh rashikbhai ",
    whatsapp: "9537777058",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Mr.refilling",
    businessType: "Cartridge refilling and Printer repair ",
    email: "apatel0233@gmail.com",
    website: "",
    address: "212 Patel shoping super market sanala road morbi ",
    visitingCard: "https://drive.google.com/open?id=1g6v9N0VmyEda2sm9Vtk-TfXTEEefMBsn"
  },
  {
    fullName: "Khavadiya sandip mulajibhai",
    whatsapp: "9725555594",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Goral agri process",
    businessType: "Sotex plant all commodity ",
    email: "",
    website: "",
    address: "BHIMNATH MAHADEV ROAD OPP.LAJAI VILLAGE ",
    visitingCard: "https://drive.google.com/open?id=1TmXRHY5SuFDEQKf1_92zhYVxbGEdqkFL"
  },
  {
    fullName: "Kunapara vijay bhai nagar bhai",
    whatsapp: "9825281350",
    village: "SARA",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "SELZIA IMPEX ROMATIRIYAL BACKWASH POWDER",
    businessType: "BACKWASH POWDER  RO MEGNESITE POWDER",
    email: "kunparavijaybhai@gmail.com",
    website: "",
    address: "Bharat nagar office",
    visitingCard: ""
  },
  {
    fullName: "Bhavesh bhai  bechada",
    whatsapp: "7285815115",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Aqua cera",
    businessType: "Senitriware",
    email: "bhaveshpatel15115@gmail.com",
    website: "",
    address: "Lilapar chikdi",
    visitingCard: ""
  },
  {
    fullName: "MANISHKUMAR BALDEVBHAI AERVADIYA",
    whatsapp: "9909458292",
    village: "TIKAR",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "VNC INPEX",
    businessType: "ALL TYPE NANO POLISHING PED AND LIQUID ",
    email: "vihanimpex157@gmail.com",
    website: "",
    address: "Ceramic plaza-1, 8-A, N.H, Morbi-363642",
    visitingCard: "https://drive.google.com/open?id=1VxsSiouem5rYD0jI66r60cZMIUkpj3Uz"
  },
  {
    fullName: "Arvadiya Kiranbhai Ishwarbhai ",
    whatsapp: "9427709177",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Shakti Oil Industries ",
    businessType: "GROUND NUT OIL",
    email: "kiranaervadia@gmail.com",
    website: "",
    address: "At- Andarna, Ta. Morbi ",
    visitingCard: "https://drive.google.com/open?id=1MCll-qzI4gZ123abYp85ozYUfzh5W7Lp"
  },
  {
    fullName: "KHANDIVAR ASHVIN SUKHADEVBHAI",
    whatsapp: "9099090941",
    village: "Ingorala",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "INDICERA WORLD",
    businessType: "Export IMPORT",
    email: "info@indicera.co.in",
    website: "www.indiceratiles.com",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1JQfpCByX_MaYi77qN9H8Y5OTi-Pv0Lam"
  },
  {
    fullName: "Kiran baldevbhai parejiya",
    whatsapp: "7359888628",
    village: "Danawada",
    taluka: "Muli",
    bloodGroup: "AB+",
    businessName: "Angelone ",
    businessType: "Share bajaar , finance ,investment , stock market ",
    email: "",
    website: "",
    address: "228, 2nd floor  , kohinoor complex, kenal road , morbi",
    visitingCard: ""
  },
  {
    fullName: "Gothi dhaval jivarajbhai ",
    whatsapp: "7990930211",
    village: "Juna Ghanshyamgadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "JB IMPEX ",
    businessType: "Raw material ( back wash )",
    email: "jbimpex1996@gmail.com",
    website: "",
    address: "Office no 5&6, ground floor, near iti college, Bharat Nagar morbi 2 ",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya haresh chaganbhai",
    whatsapp: "9879688898",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Zalavad trading ",
    businessType: "Anaj kariyanu ",
    email: "",
    website: "",
    address: "A27 marketing yard Sanala road Morbi ",
    visitingCard: "https://drive.google.com/open?id=15sVFYLQV_SG_vEezRGqVvklMsyC5TZgX"
  },
  {
    fullName: "Jalariya kantilal valjibhai",
    whatsapp: "9979473851",
    village: "Manpur",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Vijayvargiy electric",
    businessType: "Electric shop",
    email: "",
    website: "",
    address: "Shivaji weight bridge baju ma, dhuva, morbi",
    visitingCard: ""
  },
  {
    fullName: "JAKASHANIYA KAUSHIK MAHADEVBHAI",
    whatsapp: "8866773982",
    village: "Ramgadh",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "AKSHAR CERAMIC MALL",
    businessType: "Tiles Ritelar",
    email: "aksharenterprise.in@gmail.com",
    website: "",
    address: "Akshar ceramic mall , Mahendra nagar chowkdi, Morbi-2 ",
    visitingCard: "https://drive.google.com/open?id=11tlMPdRQn_mcKv2Fyz9Nrgd7mtaTto39"
  },
  {
    fullName: "Rajnish Araniya",
    whatsapp: "9925644707",
    village: "Vakiya",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Mechwell Engineering",
    businessType: "Machine manufacturers ",
    email: "jaydeepengineering@gmail.com",
    website: "",
    address: "8, A National Highway, Timbdi patiya, Morbi- 363642",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya nilesh karamshibhai",
    whatsapp: "9825628251",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Gnapath school ",
    businessType: " School ",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Surani Meet Jitendrabhai ",
    whatsapp: "7575011271",
    village: "Bavli",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Mangalam clinic ",
    businessType: "Clinic",
    email: "meetpatel3707@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "ANILKUMAR SHANTILAL MALVANIYA",
    whatsapp: "9898120978",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Jayshakti multy service ",
    businessType: "All type online work",
    email: "anilpatel2786@gmail.com",
    website: "",
    address: "1 branch...Opp cng gas pump, MahendraNagar morbi. 2nd branch   behind avadh pan near bus stop charadva",
    visitingCard: ""
  },
  {
    fullName: "KERALIYA MILESHKUMAR SHANKARLAL ",
    whatsapp: "9824262526",
    village: "LIMLI",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "KERALIYA & ASSOCIATE ",
    businessType: "CHARTERED ACCOUNTANT",
    email: "mileshkeraliya1986@gmail.com",
    website: "",
    address: "Office No-320, Landmark Arcade, Near Vinayak Honda Showroom, Sanala Road, Morbi-363641.",
    visitingCard: "https://drive.google.com/open?id=1cEYX50gF_Wc13jErv413LRBisLZEbSFW"
  },
  {
    fullName: "Sherasiya Bhavesh Arvindbhai",
    whatsapp: "9408719651",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "ID ENTERPRISE",
    businessType: "Tiles & Sanitaryware Trading",
    email: "identerprise20@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1HCN94R4ST-pSfrzz8A2MPBdRsjikpO7j"
  },
  {
    fullName: "Makasana Mayank Pravinbhai",
    whatsapp: "9909988455",
    village: "Kadiyana",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sunhearrt Ceramik",
    businessType: "Tiles Manufacturing",
    email: "Mayank@sunhearrt.com",
    website: "Www.sunhearrt.com",
    address: "8-a national highway , dhuva",
    visitingCard: ""
  },
  {
    fullName: "Fultariya Atul bhai Kashvji bhai ",
    whatsapp: "9726126501",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Hi gloss nano technology ",
    businessType: "Row material ",
    email: "HIGLOSSNANOTEC@GMAIL.-COM ",
    website: "",
    address: "Timbadi Morbi ",
    visitingCard: ""
  },
  {
    fullName: "Bhorniya rajnikant Tribhovan bhai ",
    whatsapp: "9909626745",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Ceramic contractor ",
    businessType: "Leber contractor ",
    email: "Rajni2057patel@mail.com",
    website: "",
    address: "Morbi ",
    visitingCard: ""
  },
  {
    fullName: "Patel Rajendra kumar bachubhai",
    whatsapp: "9428917760",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Sanitary ware painter",
    businessType: "Painter contract",
    email: "wwwraj78061@gmail.com",
    website: "9428917760",
    address: "Rangpar. Raj tranding",
    visitingCard: ""
  },
  {
    fullName: "Dharmendra Araniya ",
    whatsapp: "9879485400",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "DITYA AGRI TRADE",
    businessType: "All types of commodity items trading",
    email: "",
    website: "",
    address: "At- vankiya, halvad",
    visitingCard: "https://drive.google.com/open?id=1puzer2JblFUf20fE0rc29trIQ98-mOFP"
  },
  {
    fullName: "Sanghani akash nandlal bhai",
    whatsapp: "9067834725",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sidhivinayak coal ",
    businessType: "Coal trading ",
    email: "akashsanghani94@gmail.com",
    website: "",
    address: "Timbdi  morbi",
    visitingCard: "https://drive.google.com/open?id=1PWkA4PzBxFZWaR_DOjlSeZS6PIPu9k_O"
  },
  {
    fullName: "Jashapara ravikumar maganbhai",
    whatsapp: "9979298787",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sadguru industries ",
    businessType: "Glass powder ",
    email: "patelravi4415@gmail.com",
    website: "",
    address: "Sunfield ceramic,Juna ghutu road,morbi",
    visitingCard: "https://drive.google.com/open?id=1Nvxx6haBtlTfdtU3KgAfsAo85fry52Am"
  },
  {
    fullName: "Karodiya Tusharkumar Dhanjibhai ",
    whatsapp: "8200362198",
    village: "Ranjitgadh",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Gurukrupa Enterprises ",
    businessType: "Treding Tiles & Sanitaryware",
    email: "tusharkarodiya83471@gmail.com",
    website: "",
    address: "Shop no.411, Shivam Complex, Opp Trade Center, Halvad Road, Mahender nagar, Morbi 2",
    visitingCard: ""
  },
  {
    fullName: "PATEL DHARMENDRA T ",
    whatsapp: "9979844415",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "INDIAN ROADLINES ",
    businessType: "TRANSPORT ",
    email: "Indianroadlinesmorbi@gmail.com",
    website: "",
    address: "OPPOSITE CNG GES PUMP, MAHENDRANAGAR NAGAR CHOKDI , HALVAD ROAD,  MORBIHALVAD ROAD MORBI - 363642",
    visitingCard: "https://drive.google.com/open?id=1xRwe-GElHX_PbZXx6Q9E_abZ3HpBfLYh"
  },
  {
    fullName: "Sherasiya Bhavesh Arvindbhai",
    whatsapp: "9408719651",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "ID ENTERPRISE",
    businessType: "Colloidal Silica Solution ",
    email: "identerprise20@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1AFYxtCM7Mi7-Mvrh6i0SC8MTxecALG4J"
  },
  {
    fullName: "Ghumaliya ramnik bhai jaynti bhai",
    whatsapp: "9913993125",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Gopinath motars",
    businessType: "Own",
    email: "gopinath1745@gmail.com",
    website: "",
    address: "Behind shivam hospital, mahendranagar",
    visitingCard: "https://drive.google.com/open?id=1MiMZu3XZY7BWG9aO4zsIg8kzT1qFakaq"
  },
  {
    fullName: "Makasana Nikunj GhanshyamBhai",
    whatsapp: "9724761461",
    village: "Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Ceramic canteen ",
    businessType: "Canteen ",
    email: "nikunjmakasana9@gmail.com",
    website: "",
    address: "Landecor ceramic Sultanpar Road, wakaner highway ",
    visitingCard: ""
  },
  {
    fullName: "Patel Mehul tribhovanbhai ",
    whatsapp: "9902511890",
    village: "Kuntalpur",
    taluka: "Muli",
    bloodGroup: "AB+",
    businessName: "Saanvi ceramic ",
    businessType: "Tiles",
    email: "saanviceramics@gmail.com",
    website: "",
    address: "",
    visitingCard: "https://drive.google.com/open?id=1-YV-EtcS0_8959WZPdVDI6ItT3S67d2J, https://drive.google.com/open?id=1L6b-Hb_lWVvKkBs4A4w4Ef8ocZEUyHzr"
  },
  {
    fullName: "HULANI MUKUND GANESHBHAI",
    whatsapp: "9586300993",
    village: "Mangadh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "CERABIZZ CORPORATION ",
    businessType: "Tiles & sanitary trading",
    email: "cerabizzcorporation00993@gmail.com",
    website: "",
    address: "Dharamgold complex , near old Kuber cinema , 8-a national highway morbi",
    visitingCard: "https://drive.google.com/open?id=1FM100UK_W2sCTkYUn7CspGr_xCsCh_l4"
  },
  {
    fullName: "Aghara Pravinbhai Tribhovanbhai",
    whatsapp: "9825448598",
    village: "Survadar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "K B Corporation ",
    businessType: "Chemical ",
    email: "Deepaghara7654@gmail.com",
    website: "",
    address: "Housing Board, Morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Dalsaniya maheshbhai maganbhai",
    whatsapp: "7016866566",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "La ceramica",
    businessType: "Tile trading",
    email: "Maheshpatel2587@gmail.com",
    website: "",
    address: "201 Akshar business center rafadiya",
    visitingCard: ""
  },
  {
    fullName: "Dalsaniya darshankumar gunvantbhai",
    whatsapp: "9913155556",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Aavkar Hydraulic pipe& forclip",
    businessType: "Hydraulic ",
    email: "Dalsaniyadarshan2@gmail.com",
    website: "",
    address: "Jetpar pipli road",
    visitingCard: ""
  },
  {
    fullName: "MAKASANA VIJAYKUMAR GHANSHYAMBHAI",
    whatsapp: "9924052326",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "UNION BANK OF INDIA",
    businessType: "Service in bank",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Loriya amit thobhan bhai",
    whatsapp: "9879309814",
    village: "Vaghagadh ",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Teacher",
    businessType: "Gyanpath Vidhyalay partner",
    email: "amitloriya@gamil.com",
    website: "-",
    address: "New Gujarat housing board Morbi",
    visitingCard: ""
  },
  {
    fullName: "Maravaniya Prayagkumar Talsibhai",
    whatsapp: "9638099899",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "A-",
    businessName: "Bhuvneshwar Pack Print ",
    businessType: "Manufacturer of all types of corrugated box",
    email: "prayagmaravaniya@gmail.com",
    website: "",
    address: "Lakhadhirpur Road, 8-A National Highway, Morbi - 2.",
    visitingCard: "https://drive.google.com/open?id=1Pdqyu9ACjgqHHm7XFX02B6OuEvJtUmKd"
  },
  {
    fullName: "VARMORA DHAVALKUMAR BALVANTRAY",
    whatsapp: "9033429800",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "IYOTA TILES LLP",
    businessType: "Ceramic wall tiles ",
    email: "varmora_dhaval@yahoo.com",
    website: "",
    address: "Dhuva wankaner",
    visitingCard: "https://drive.google.com/open?id=1XsZta2-C1j_hpTDtiLghQKEHnu0AIlxQ"
  },
  {
    fullName: "Dalsaniya jayeshbhai khimjibhai",
    whatsapp: "9904545555",
    village: "Kidi",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Swell granito llp",
    businessType: "Ceramic",
    email: "Jashdalsaniya@gmail.com",
    website: "",
    address: "Sartanpar road ratavirda wankaner",
    visitingCard: "https://drive.google.com/open?id=1MsfObBFfZFCkntq1ILFPfMCVmPXpPGes"
  },
  {
    fullName: "Lalit kumar Sukhdev bhai Khandivar",
    whatsapp: "9925699376",
    village: "Ingorala",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Patidar Stationery & Graphics",
    businessType: "Ceramic & Office Statonery & Printing Solution",
    email: "lalitkhandivar@gmail.com",
    website: "",
    address: "Dharti Tower, Near Old St stand, Sardar Road Morbi",
    visitingCard: "https://drive.google.com/open?id=1b4XF_pkdZ36h-rvPGGvjRh8mkpJKBf29"
  },
  {
    fullName: "VIDJA JAYNTIBHAI RAMJIBHAI",
    whatsapp: "9925173240",
    village: "NAVA DEVALIYA",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "CLASSIC AUTO MOBILES",
    businessType: "All car spare parts",
    email: "Vishalvidja3727@gmail.com",
    website: "",
    address: "GIDC opp renault showroom near rewa township sanala road morbi-1",
    visitingCard: ""
  },
  {
    fullName: "KHAVADIYA JAY LALJIBHAI",
    whatsapp: "6353529355",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "ISRAEL SEEDS CORPORATION ",
    businessType: "ALL TYPE OF SEEDS MANUFACTURER ",
    email: "israelseedscorporation@gmail.com",
    website: "",
    address: "*Israel seeds corporation*  Sr.no 613, At po :- Medrapura (Kotadi) Behind jay prabhu cotton ind. Vijapur-Mehsana highway Ta:- Vijapur  Do:-Mehsana",
    visitingCard: ""
  },
  {
    fullName: "Nandana kalpeshbhai mahadavbhai",
    whatsapp: "9913192023",
    village: "Lelapur",
    taluka: "Lakhtar",
    bloodGroup: "",
    businessName: "Velocity car service",
    businessType: "Car service",
    email: "kalpeshpatel96013@gmail.com",
    website: "",
    address: "Nr. Dav petroleum mahendarnagar chowkdi , mahendarnagar morbi-2",
    visitingCard: ""
  },
  {
    fullName: "Lo Amit Kumar Ghanshyam bhai",
    whatsapp: "9998949366",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Bajarang moters accersris ",
    businessType: "Car 🚗 motres and accessories ",
    email: "amitpatel11180@gmail.com",
    website: "",
    address: "Mahendrngar morbi iti college ni same ",
    visitingCard: ""
  },
  {
    fullName: "PATEL TUSHARBHAI BHAVESHBHAI",
    whatsapp: "8460059828",
    village: "Lakhtar",
    taluka: "Lakhtar",
    bloodGroup: "AB-",
    businessName: "Maruti sales agency ",
    businessType: "Wholesale agency ",
    email: "tbpatel30798@gmail.com",
    website: "",
    address: "Near gau sala gate lalper",
    visitingCard: ""
  },
  {
    fullName: "Aravadiya Bharatbhai keshavjibhai",
    whatsapp: "9979946887",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "O-",
    businessName: "Shree umiya roadlines",
    businessType: "Transporter",
    email: "aravadiyab@gmail.com",
    website: "",
    address: "Mehndranagar chowkdi, ghuturoad, morbi",
    visitingCard: ""
  },
  {
    fullName: "Aervadiya prince bharat bhai",
    whatsapp: "7435901517",
    village: "Vaghagadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "SHUBH CREATION ",
    businessType: "Clothing (Brand)",
    email: "Aervadiyaprince@gmail.com",
    website: "",
    address: "L-579,opp Bajarang pan,sakti nagar society,Gujarat housing board,chhatralay road,morbi",
    visitingCard: ""
  },
  {
    fullName: "Jaypal Avacharbhai Khavadiya",
    whatsapp: "9727156431",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Deca Micron Pvt Ltd ",
    businessType: "Manufacturer of Calcium Carbonate ",
    email: "jaypal.khavadiya89@gmail.com",
    website: "",
    address: "Ahemdabad",
    visitingCard: "https://drive.google.com/open?id=12ICezfmpYMG5LE4pw3BK8dbTRlbrk4qA"
  },
  {
    fullName: "Dilipbhai thobhanbhai kaila",
    whatsapp: "9737170007",
    village: "Vaghagadh ",
    taluka: "Dhrangdhra",
    bloodGroup: "O-",
    businessName: "Hospital ",
    businessType: "Hospital ",
    email: "Dilipkaila1983@gmail.com",
    website: "",
    address: "Sanala road,B/H mahesh hotel",
    visitingCard: ""
  },
  {
    fullName: "KANDIYA KASHYAP NITINBHAI",
    whatsapp: "9558368345",
    village: "Lakhtar",
    taluka: "Lakhtar",
    bloodGroup: "AB+",
    businessName: "GIGWELL SERVICES LLP",
    businessType: "SERVICE",
    email: "KASHYAPKANDIYA9@Gmail.com",
    website: "GIGWELLservices.com",
    address: "Golden market , ravaper-ghunda Road,morbi",
    visitingCard: ""
  },
  {
    fullName: "MALVANIYA KAUSHIK MAHESHBHAI ",
    whatsapp: "9512444435",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Kaushik M Malvaniya & Associates ",
    businessType: "C.A Office",
    email: "kaushikpatel1622000@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Bapodariya Vijaybhai ishwarbhai",
    whatsapp: "9979134981",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Tirupati Water supplies ",
    businessType: "Mineral water plant ",
    email: "bapodariyajaimin@gmail.com",
    website: "",
    address: "Sakat sanala",
    visitingCard: ""
  },
  {
    fullName: "Satapara Dhaval Prakashbhai ",
    whatsapp: "7046462626",
    village: "Lakhtar",
    taluka: "Lakhtar",
    bloodGroup: "",
    businessName: "Idencis Deaign Studio ",
    businessType: "Ceramic tiles design development and all type of branding ",
    email: "Dhaval007.sd@gmail.com ",
    website: "",
    address: "Morbi ",
    visitingCard: ""
  },
  {
    fullName: "Kaila Manojbhai Chandubhai",
    whatsapp: "9913442122",
    village: "Vaghadh",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Monza Granito Pvt Ltd ",
    businessType: "Ceramic ",
    email: "manojkaila7952@gmail.com",
    website: "",
    address: "151/Pipadi road, opp. Vivanta ceramic, Bela",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya prince jayantibhai",
    whatsapp: "9558155606",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Kivana Tradelink ",
    businessType: "Feldspar (soda potash)",
    email: "Princekhavadiya55@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Vidja Harshad Devkaranbhai ",
    whatsapp: "7359655010",
    village: "Jodhapar nadi",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "MARUTI ROADWAYS ",
    businessType: "Transport,Powdar",
    email: "vidjaharshadd@gmail.com ",
    website: "",
    address: "Morbi-2",
    visitingCard: ""
  },
  {
    fullName: "MALVANIYA CHINTAN GANESHBHAI ",
    whatsapp: "9033336656",
    village: "SARA",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "SHREE HARI ACCOUNT CONSULTANT ",
    businessType: "ACCOUNTING",
    email: "chintanmalvaniya@gmail.com",
    website: "",
    address: "Arohi chember3 ,near gspc gas office",
    visitingCard: ""
  },
  {
    fullName: "Ubhadiya Montu kumar vasudev bhai ",
    whatsapp: "9664733477",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Vitrified G.M job",
    businessType: "Job ",
    email: "ubhadiyamontu@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Arvadiya jimmy natvarbhai",
    whatsapp: "7990635652",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "ABDHI FOODS",
    businessType: "Wholesaler",
    email: "jimmyarvadiya454@gmail.com",
    website: "",
    address: "Avni chokdi ,morbi",
    visitingCard: ""
  },
  {
    fullName: "DILIPBHAI DHANJIBHAI SANGHANI",
    whatsapp: "9904976089",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "O-",
    businessName: "ACCOUNTING ",
    businessType: "Service",
    email: "dsanghani1970@gmail.com",
    website: "No",
    address: "Shivpark society cenal road near Nirmal vidhyalay opp.shubhash nagar Morbi.",
    visitingCard: ""
  },
  {
    fullName: "TALVANIA VINODBHAI KARSHANBHAI",
    whatsapp: "9979020311",
    village: "Vaghgadh ",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "GYANPATH VIDHYALAY, ",
    businessType: "SCHOOL",
    email: "Vkpatelmorbi@gmail.com",
    website: "",
    address: "New Guj.Housing Bord Morbi",
    visitingCard: ""
  },
  {
    fullName: "Khavadiya harshil hasmukhbhai",
    whatsapp: "8849140580",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Bahuchar agro - mahendranagar ",
    businessType: "Wholesaler of Pesticides & Seeds",
    email: "khavadiyajay55@gmail.com",
    website: "",
    address: "Shop no 4 , Bapa sitaram complex , mahendranagar chowkdi, morbi -2",
    visitingCard: "https://drive.google.com/open?id=1Q1GF5GhYO49znB9hGCEMSP_lS9_P-Ks8"
  },
  {
    fullName: "Khavadiya valabhbhai audhavjibhai",
    whatsapp: "9714774962",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B-",
    businessName: "Ceramic water suppliers ",
    businessType: "Ceramic ",
    email: "",
    website: "",
    address: "Dhuva matel rode,morbi",
    visitingCard: "https://drive.google.com/open?id=1Bj51IG5cL0vt9f9kH8d5o7p1DQTKNHwT"
  },
  {
    fullName: "Patel Anand Jivram Bhai ",
    whatsapp: "8000029998",
    village: "Shidhasr ",
    taluka: "Muli",
    bloodGroup: "",
    businessName: "1) .Aqista Unify LLP  2). Texona Sink LLP ",
    businessType: "1).Adhesive epoxy Grout 2). Qaurtz Sink.",
    email: "Patelanand106@gmail.com ",
    website: "",
    address: "S.R.No.116, 8-A national highway Beside",
    visitingCard: ""
  },
  {
    fullName: "Sherasiya Tejash Harji bhai",
    whatsapp: "9825987870",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Lambent Nanochemicals",
    businessType: "Nano chemical , A & C",
    email: "office.lambent@gmail.com",
    website: "www.lambentnanochemicals.com",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1_jUvnbxP6Gl55q1Fu4_aLE5rYehgACqp"
  },
  {
    fullName: "Fultariya Atulkumar kanjibhai ",
    whatsapp: "9726320567",
    village: "Pratapgarh ",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Space Enterprise ",
    businessType: "Diamond tools and abrasive ",
    email: "space.ent310@gmail.com",
    website: "",
    address: "Shakti chamber 2, 8 A national Highway, Shop no 33, Morbi ",
    visitingCard: "https://drive.google.com/open?id=1jbjqW0SsIQiqPocdszWqYCr2cBgUMZHo"
  },
  {
    fullName: "DETROJA RAJ KANTILAL",
    whatsapp: "7984290515",
    village: "Survadar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Battery Point ",
    businessType: "બેટરી અને ઇન્વર્ટર ",
    email: "rajeshpatel9909541101@gmail.com",
    website: "",
    address: "Sky line shoping , near GSPC gas office Umiya Circle ",
    visitingCard: ""
  },
  {
    fullName: "Andarpa nilesh gordhanbhai",
    whatsapp: "9925486284",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Niom aentarparis ",
    businessType: "Cctv cemera",
    email: "nilesh86284@gmail.com",
    website: "",
    address: "Rangapa",
    visitingCard: ""
  },
  {
    fullName: "Arvadia Hirenkumar Vinodray",
    whatsapp: "9979853049",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Ashok Industries ",
    businessType: "Manufacturing of Aluminium Section",
    email: "ashok.alu.industries@gmail.com",
    website: "",
    address: "Plot no 223-224, rafaleshwar gidc morbi",
    visitingCard: "https://drive.google.com/open?id=14ECcoCT_2yrjOZDk9RYfFC6rHs0yidXe"
  },
  {
    fullName: "SATAPARA PARESHKUMAR BHAVJIBHAI",
    whatsapp: "8980804196",
    village: "DHOLI",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "MARUTINANDAN ENTERPRISE ",
    businessType: "ALL TYPE OF FORKLIFT SPARE PARTS",
    email: "marutinandanenterprise2024@gmail.com",
    website: "",
    address: "SHOP NO-13, SHREENATH COMPLEX,NEAR TRAJPAR CHOKDI,MORBI",
    visitingCard: "https://drive.google.com/open?id=1JsyNE_P615I164nFsmbnvZhWaBDojUuZ"
  },
  {
    fullName: "PRAGNESHKUMAR GORDHANBHAI PATEL ",
    whatsapp: "9106442025",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "WORLDWORTH CORPORATE ",
    businessType: "MS STEEL (TMT & STRUCTURE)",
    email: "alwaysright3298@gmail.com",
    website: "",
    address: "MORBI",
    visitingCard: "https://drive.google.com/open?id=1mIo0mmJoQMH0soais0812qfhkhgTJPBZ"
  },
  {
    fullName: "Vidja Rameshbhai Muljibhai",
    whatsapp: "9825268625",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "ArthWork JCB ",
    businessType: "Machis bhade apva mate",
    email: "",
    website: "",
    address: "Morbi-2",
    visitingCard: ""
  },
  {
    fullName: "ARVADIA VITAN MANSUKHBHAI ",
    whatsapp: "7016980865",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "SUNRISE ELECTRICALS ",
    businessType: "TRADING OF INDUSTRIAL ELECTRICAL SWITCHGEAR",
    email: "sunrise.electricals03@gmail.com",
    website: "",
    address: "SARTANPAR ROAD NEAR SUNGLARE VITRIFIED MORBI-363642",
    visitingCard: "https://drive.google.com/open?id=1iEwP8Qz8cXjFrTmzn4k0CFDFeWYMEjNK"
  },
  {
    fullName: "GOTHI DIPAKBHAI SAVJIBHAI ",
    whatsapp: "9979999527",
    village: "AJITGADH",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "NIV TILES ",
    businessType: "CERAMIC TRADING ",
    email: "dipaksgothi@gmail.com",
    website: "",
    address: "Tulshi chambers old Ghuntu road, trajpar cross road, morbi-363642",
    visitingCard: "https://drive.google.com/open?id=1HfZoaXTlVBJEJqSYtOtbmTgjEXBryBZq"
  },
  {
    fullName: "Bopaliya Rakesh Ratilal",
    whatsapp: "8320875950",
    village: "Vaghgadh ",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Alord ceramic",
    businessType: "Ceramic tiles trading",
    email: "smartboy301189@gmail.com",
    website: "",
    address: "508 empire square opp.sanora ceramic mahendranagar",
    visitingCard: "https://drive.google.com/open?id=1ZSbvI__i_pqBjnS4FIHZbt1zr30TX-xZ"
  },
  {
    fullName: "SERASIYA TEJASHKUMAR HARJIVANBHAI",
    whatsapp: "9825987870",
    village: "AJITGADH",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "LAMBENT CHEMICALS",
    businessType: "CHEMICAL MANUFACTURER",
    email: "tjs.srsy@gmail.com",
    website: "www.lambentnanochemicals.com",
    address: "Morbi",
    visitingCard: "https://drive.google.com/open?id=1ZpE9GmH4HMH1KTCLv0dXBPFk8Bq7CTDZ"
  },
  {
    fullName: "Khavadiya Prabhulal Arjanbhai",
    whatsapp: "9925844722",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Uma Account Associated ",
    businessType: "Account ",
    email: "prabhukhavadiya@gmail.com",
    website: "",
    address: "2nd Floor, Near Nakshtra Hospital, B/h Kalrav Hospital, Apple Hospital Street, Sanala Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "BAPOLIYA RAJENDRABHAI K.",
    whatsapp: "9909459046",
    village: "Vaghgadh ",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Uma water saplayarsh",
    businessType: "Harikushn mogec",
    email: "pr173595@gmail.com",
    website: "",
    address: "Hariom park ghuntu.",
    visitingCard: ""
  },
  {
    fullName: "KHAVADIYA AMIT BHAGVANJIBHAI",
    whatsapp: "9726052004",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "ACCONTANT",
    businessType: "ACCOUNT",
    email: "amitkhavadiya1990@gmail.com",
    website: "",
    address: "UMA ACCOUNT ASSOCIATES NEAR- NAKSHTRA HOSPITAL APPLE HOSPITAL STREET SANALA ROAD MORBI",
    visitingCard: ""
  },
  {
    fullName: "Moradiya Ashokbhai Ramjibhai",
    whatsapp: "9979070805",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "KISHAN ENGINEERING WORKS",
    businessType: "Ceramic Lab Machinery Manufacturer",
    email: "ashokrmoradiya@gmail.com",
    website: "https://www.kishaneng.in",
    address: "8-A National Highway,Near GK Hotel,Trajpar Char Rasta,Morbi-2",
    visitingCard: "https://drive.google.com/open?id=1RIWuEEkzITzuWmWxWn2G1seZKVNJX77V"
  },
  {
    fullName: "Marvaniya yatin bhai tarshi bhai",
    whatsapp: "8980695958",
    village: "Samli",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Yatin pack print",
    businessType: "Packaging ",
    email: "Yatinmarvaniya@gamil.com",
    website: "",
    address: "Old ghuntu road opp.zealtop vitrified ",
    visitingCard: "https://drive.google.com/open?id=1prMBRVvy703SojHHbodNQlX0orFu2P4g"
  },
  {
    fullName: "Sanghani anand kumar rameshbhai",
    whatsapp: "7043254745",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "GURU EMPORIUM & TAILOR",
    businessType: "Shuting - shirting",
    email: "Sanghanianand6397@email.com ",
    website: "",
    address: "Jalaram complex, khoja khana sheri, Dr. Tkhtshihji road, morbi",
    visitingCard: "https://drive.google.com/open?id=1VxgH4-8jwyatSNb9ntpvCAbitEw5Td2k"
  },
  {
    fullName: "Khavadiya Dipak Hansrajbhai",
    whatsapp: "9979071311",
    village: "Krushnanagar (Nava Ratabher)",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Jyoti Art Photography ",
    businessType: "LED Screen ",
    email: "harshadkhavadiya71311@gmail.com",
    website: "",
    address: "Elora Shopping Opp. New Bus Stand Shanala Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Varmora kamleshbhai Parshotambhai",
    whatsapp: "7874000555",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Creations international",
    businessType: "Ceramic Tiles Trading",
    email: "varmorakp3188@gmail.com",
    website: "",
    address: "Shakti chamber 1",
    visitingCard: ""
  },
  {
    fullName: "AGHARA KISHAN HASMUKHBHAI ",
    whatsapp: "8320648660",
    village: "N/A",
    taluka: "N/A",
    bloodGroup: "O+",
    businessName: "SUNPLUS CERA LLP",
    businessType: "Step riser & border tiles ",
    email: "kishanaghara2573@gmail.com",
    website: "",
    address: "SUNPLUS CERA LLP, OPP.ZIBON CERAMIC,AT VIRATNAGAR , RANGPAR ",
    visitingCard: ""
  },
  {
    fullName: "Akhara Dasharath bhai keshavgi bhai",
    whatsapp: "9428037637",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Pioneer engineering tools",
    businessType: "Diamond roller",
    email: "AGHARADASHRATH@YAHOO.COM",
    website: " ",
    address: "Old ghutu road, morbi",
    visitingCard: "https://drive.google.com/open?id=1_BPbbTpX9gAWZcxP5O9IQ2YAglhPhli7"
  },
  {
    fullName: "Jignesh makasana ",
    whatsapp: "9924894426",
    village: "Charadava",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Solano ceramic ",
    businessType: "Tiles ",
    email: "Solanoceramic@gmail.com",
    website: "rsgroupceramic.com",
    address: "Mahendranagar",
    visitingCard: ""
  },
  {
    fullName: "Dalsaniya Jayendra Amrutlal ",
    whatsapp: "9825506992",
    village: "Jasapar",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Ganesh Enterprise / R J Moline ",
    businessType: "Manufacturing ",
    email: "jayu9699@yahoo.com",
    website: "",
    address: "Sakti chamber / Udaipur / jaipur ",
    visitingCard: ""
  },
  {
    fullName: "Arvadiya krunal kumar jayantilal",
    whatsapp: "8306017917",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Kemi pest control ",
    businessType: "Fumigation service ",
    email: "kemipestcontrol@gmail.com",
    website: "",
    address: "Prabhat chembar, mahendranagar , morbi",
    visitingCard: "https://drive.google.com/open?id=18bCr1e7SeapNI0XxZKq69mncBUwFNdFt"
  },
  {
    fullName: "Khavdiya manoj Bhai keshvaji bhai",
    whatsapp: "9925337153",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Loren ceramic ",
    businessType: "Tiles marketing ",
    email: "Manojpatel.mp778@gmail.com",
    website: "",
    address: "Old ghuntu road morbi",
    visitingCard: ""
  },
  {
    fullName: "Sanghani jignesh maganbhai",
    whatsapp: "9909172742",
    village: "Ravapar boni park",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Bajrang plastic ",
    businessType: "Molding ",
    email: "sanghanijignesh2750@gmail.com",
    website: "",
    address: "Niyar patel transport manager 1",
    visitingCard: ""
  },
  {
    fullName: "MARVANIYA PRAKASHBHAI PRABHUBHAI",
    whatsapp: "9726916268",
    village: "VANKIYA",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "MARUTI ACCOUNTING",
    businessType: "ACCOUNT SERVICE",
    email: "prakashmarvaniya@gmail.com",
    website: "",
    address: "JETPAR ROAD, SHUBH CORPORATION HUB,FLOOR NO.5 , SHOP NO 518,MAHENDRANAGAR MORBI",
    visitingCard: ""
  },
  {
    fullName: "Moradiya Niraj Rameshbhai",
    whatsapp: "9512029564",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "ITOLI GRANITO LLP",
    businessType: "Tiles Manufacturer ",
    email: "nirajmoradiya@yahoo.com",
    website: "https://www.itoli.co",
    address: "At:Sartanpar,Dist.:Morbi-363641",
    visitingCard: "https://drive.google.com/open?id=1cC69EzE7W0jQyFZoWK0nZlK_ONFgcNaO"
  },
  {
    fullName: "Khandivar Jitendra Ghoghaji bhai",
    whatsapp: "9978588188",
    village: "Ingorala",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "ALY Microns Llp  & Alystone Microns llp & Somnath ceramic ",
    businessType: "Soda , potash wash plants ",
    email: "Jitendrakhandivar918@gmail.com",
    website: "",
    address: "Nichimandal, Morbi Halvad Road",
    visitingCard: ""
  },
  {
    fullName: "Bhoraniyabrijesh",
    whatsapp: "8141458455",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Lucian ceramic ",
    businessType: "Tiles",
    email: "Bhoraniyabrijesh4@gmail.com",
    website: "",
    address: "Old ghuntu road morbi- 2",
    visitingCard: "https://drive.google.com/open?id=1xn8fOjQtmNDxY-k16yqW1ixpCupFIH1v"
  },
  {
    fullName: "Bhavesh R Moradiya",
    whatsapp: "9512029562",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Itoli Granito LLP",
    businessType: "Manufacturing of GVT Tiles",
    email: "info@itoli.co",
    website: "www.itoli.co",
    address: "Itoli Granito LLP, Sartanpar Road, Tita Chokdi, Wankaner, Morbi",
    visitingCard: "https://drive.google.com/open?id=1-mZ9doeqYYcjU-zNPVSOi3oyjEPO0jlm"
  },
  {
    fullName: "Makasna Bharatbhai Ambarambhai",
    whatsapp: "9825488866",
    village: "Kadiyana",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Anand cement industry",
    businessType: "Coal business ",
    email: "bapatel4@gmail.com",
    website: "",
    address: "Anand cement industry, 27 A National Highway, Dhuva Morbi ",
    visitingCard: ""
  },
  {
    fullName: "Jotaniya Arvind bhai premji bhai",
    whatsapp: "9979074301",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "VM diamond tools squring whees",
    businessType: "Row material of policing line",
    email: "arvindbhaijotaniya@gmail.com",
    website: "",
    address: "Morbi2 Trajpar chokdi",
    visitingCard: ""
  },
  {
    fullName: "Kundariya Maheshbhai Ishwarbhai ",
    whatsapp: "9909652282",
    village: "Devipur",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Shree Hari Account ",
    businessType: "Accounting ",
    email: "Sha.consultant111@gmail.com",
    website: "No",
    address: "10 Arohi chamber 3 Opp Gsps Gas office, 8 NHA ,Morbi2",
    visitingCard: ""
  },
  {
    fullName: "PATEL BHAVESHBHAI JAYENDRABHAI",
    whatsapp: "9978914314",
    village: "MORBI",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "ARKITON CERAMIC ",
    businessType: "TILES",
    email: "bhaveshkiranpatel@gmail.com",
    website: "",
    address: "JETPAR ROAD",
    visitingCard: ""
  },
  {
    fullName: "Sitapara Dilip ishvarbhai",
    whatsapp: "9978554450",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Ceramic work",
    businessType: "Body quality consultant ",
    email: "Sitaparadilip1@gmail.com",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Patel Dilipbhai Ramnikbhai",
    whatsapp: "9925870690",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Camel designer Decor",
    businessType: "Decorative Tiles & pvc Cabinate ",
    email: "dilippatel22585@gmail.com",
    website: "",
    address: "Old ghuntu Road. Morbi",
    visitingCard: ""
  },
  {
    fullName: "Moradiya mukesh vashrambhai",
    whatsapp: "7777984657",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "LOREN CERAMIC ",
    businessType: "TILES TREDING",
    email: "mukeshmordiya243@gmail.com",
    website: "",
    address: "Shop no. 10. Swagat chembar,old ghuntu road morbi -2",
    visitingCard: ""
  },
  {
    fullName: "Satapara khodidas parsottam bhai ",
    whatsapp: "9978173550",
    village: "Dholi",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Ceramic sorting & packing contractor ",
    businessType: "Contractor ",
    email: "Khodidaspatel84@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: ""
  },
  {
    fullName: "Rakesh bhai Gangaram bhai kunpara ",
    whatsapp: "9638439321",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Electric ",
    businessType: "Maruti electric and inverter service ",
    email: "rp3032734@gmail.com ",
    website: "",
    address: "Nani kenal road  sanraiz vila shop no 110",
    visitingCard: "https://drive.google.com/open?id=1T4QeT2VJoMWOFo6JWkE5ht9-EGdDOro9"
  },
  {
    fullName: "Agola manojkumar ramanik bhai",
    whatsapp: "8141712877",
    village: "Godavari",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Dispatch hed",
    businessType: "Job/service",
    email: "Manojpatel81417@gmail.com ",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Mori kamlesh natvarlal",
    whatsapp: "9925489087",
    village: "Methan",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Uma mini mall mobile ",
    businessType: "Mobile ",
    email: "kamleshpatel74755@gmail.com",
    website: "",
    address: "Uma township morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Aervadiya nimesh rameshbhai",
    whatsapp: "7567217590",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Food ",
    businessType: "FMCG",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "Patel jigneshkumar Maganbhai",
    whatsapp: "9909959026",
    village: "Dholi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "KRIVETY",
    businessType: "Glaze raw material trading",
    email: "Krivety.biz@gmail.com",
    website: "",
    address: "Shop no : 27&28 seven cera mall near lords hotel jetpar-pipali road morbi-2 363642",
    visitingCard: ""
  },
  {
    fullName: "Parejiya MukeshBhai govindbhai ",
    whatsapp: "9879492959",
    village: "Dudhrej",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Bajrang tools ",
    businessType: "Carpenter ",
    email: "MukeshPatel 7436@gmail.com ",
    website: "",
    address: "Ayodhya Puri main road oop aayush hospital ",
    visitingCard: ""
  },
  {
    fullName: "BHORANIYA RASIKLAL KESHAVLAL ",
    whatsapp: "9825051767",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Shriji planning ",
    businessType: "Building planning ",
    email: "shrijiplanning@gmail.com",
    website: "",
    address: "Amitpark society b/h narsang temple Ravapar road morbi ",
    visitingCard: ""
  },
  {
    fullName: "Patel Hitesh Dineshlal",
    whatsapp: "9727770453",
    village: "Goriyavad",
    taluka: "Patadi",
    bloodGroup: "B+",
    businessName: "Wingress Ceramica ",
    businessType: "Exporter of Tiles and Sanitaryware",
    email: "hitesh.wingressceramica@gmail.com",
    website: "www.wingressceramica.com",
    address: "Office no.22, 2nd floor, Akshar Business Center, Rafadeshwar, At-Jambudia, Morbi - 363642",
    visitingCard: "https://drive.google.com/open?id=10lotnYxbxBdpCyCOrJo5c8SseqDJN-J5"
  },
  {
    fullName: "AGHARA GHANSHYAMBHAI ISHVARBHAI",
    whatsapp: "9638680005",
    village: "Dhrangadhra ",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "MOZACA GLASS COAT",
    businessType: "Raw material frit",
    email: "Mozacaglasscoat@gmail.com",
    website: "",
    address: "Jambudiya,morbi",
    visitingCard: ""
  },
  {
    fullName: "Moradiya Piyush Ghanshyambhai",
    whatsapp: "9909433334",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Imlis ceramica Llp",
    businessType: "Ceramic tiles",
    email: "Moradiyapiyush008@gmail.com",
    website: "Www.imlis.in",
    address: "Sartanpar road , morbi",
    visitingCard: "https://drive.google.com/open?id=1tj_D1bkoGG505DKSKu_8A8DiZBu26Fov"
  },
  {
    fullName: "MORADIYA MUKESH VASHRAMBHAI",
    whatsapp: "7777984657",
    village: "VANKIYA",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "LOREN CERAMIC ",
    businessType: "TILES TRENDING ",
    email: "mukeshmordiya243@gmail.com",
    website: "",
    address: "SWAGY CHEMBAR. SHOP NO-10. OLAD GHUNTU RIAD MORBI -2",
    visitingCard: ""
  },
  {
    fullName: "Bhoraniya Dineshbhai Durlabhajibhai ",
    whatsapp: "9558814014",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Umiya Computer World ",
    businessType: "Computer Sell & Service ",
    email: "umiyacomputerworld@gmail.com",
    website: "www.umiyacomputerworld.com",
    address: "Super Market , Near new bus stand , Sanala Road , Morbi ",
    visitingCard: "https://drive.google.com/open?id=1OhjKOQgKy8N3DcX2lf_nJjRrQG-PqnaB"
  },
  {
    fullName: "MAYUR MANILAL PATEL",
    whatsapp: "8866339930",
    village: "GORIYAVAD",
    taluka: "Patadi",
    bloodGroup: "B+",
    businessName: "TITANS CERAMIC ",
    businessType: "CERAMIC TRADING",
    email: "titansceramic@gmail.com",
    website: "",
    address: "Luxuria Business Park , 427 Office Number, Mahendranagar,Morbi",
    visitingCard: "https://drive.google.com/open?id=1QuGnQBgQAjcPwG1GZt2zxzJdpJ7L83Xu"
  },
  {
    fullName: "MORADIYA BHAUTIK SHANTILAL",
    whatsapp: "9909433234",
    village: "Vankiya",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "IMLIS CERAMICA LLP ",
    businessType: "GVT / PGVT Tile Manufacturing ",
    email: "bhautikmoradiya502@gmail.com",
    website: "https://www.imlis.in",
    address: "Sr No. 173/1 & 174, Sartanpar, Ratavirda Rd, Ratavirda, Gujarat 363621",
    visitingCard: "https://drive.google.com/open?id=1aXU9f9I1kZuo1tUoaxJ4UdW-nWB8MmiS"
  },
  {
    fullName: "Patel Chetanbhai Vinodbhai ",
    whatsapp: "9974405744",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Latest garden, latest group",
    businessType: "Construction (builder)",
    email: "chetanvkalariya@gmail.com",
    website: "",
    address: "Mahendra Nagar",
    visitingCard: ""
  },
  {
    fullName: "Agola Sudhir sanjaybhai",
    whatsapp: "8320827268",
    village: "Navi kidi",
    taluka: "Halvad",
    bloodGroup: "A-",
    businessName: "Gurukrupa Galas/ Aluminium ",
    businessType: "Gurukrupa Galas/ Aluminium ",
    email: "Sudhiragola@gmail.com",
    website: "",
    address: "Panchasar Road Radhekrishna ni same morbi- 363641",
    visitingCard: ""
  },
  {
    fullName: "Fultariya hasmukhbhai Kanjibhai ",
    whatsapp: "7984951290",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Squaring diamond wheels ",
    businessType: "Row material of policing line ",
    email: "smitfultariya67@gmail.com",
    website: "https://www.shreejiimpex.org.in",
    address: "Plot No - 6, Anand Nagar, N.H.27, Trajapar,, Morbi, Gujarat, 363642, India",
    visitingCard: "https://drive.google.com/open?id=1mdZruQDHvt41hqbaWZPl2SHIjMxs4uYK"
  },
  {
    fullName: "Mori Chetan bhagvanji bhai",
    whatsapp: "9925983901",
    village: "methan",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Patel pan ",
    businessType: "Shop of cold drinks and pan masala ",
    email: "chetanmori36@gmail.com",
    website: "",
    address: "Makansar(Gokulnagar),wakaner highway, Morbi ",
    visitingCard: ""
  },
  {
    fullName: "Arvadia Ashishkumar Mansukhbhai",
    whatsapp: "7984935406",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Sun Electricals ",
    businessType: "Trading of electrical switchgear ",
    email: "sunelectricals03@gmail.com",
    website: "",
    address: "9/10,Akshar Business Centre,8-A National Highway, Rafadeshwar",
    visitingCard: "https://drive.google.com/open?id=1pY2lMAJSRN9OCACm1OxvH52cTUJzBsBN"
  },
  {
    fullName: "PATEL HIRENKUMAR JAGJIVANBHAI",
    whatsapp: "9909393387",
    village: "NAGADAKA",
    taluka: "Patadi",
    bloodGroup: "B+",
    businessName: "EXPORT MANAGER",
    businessType: "JOB/SERVICE",
    email: "hirenahajoliya@gmail.com",
    website: "",
    address: "",
    visitingCard: "https://drive.google.com/open?id=1wVSQ70Y14tEXJCwD_7CwRIuZm6QT51p-"
  },
  {
    fullName: "Jignesh patel",
    whatsapp: "9727105031",
    village: "Haripar",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Rockstar truss light",
    businessType: "Sounds _ steg lights  decorations ",
    email: "Shreejiliveyou5031@email.com",
    website: "",
    address: "Morbi_ surat",
    visitingCard: ""
  },
  {
    fullName: "Manoj Bhagavanji bhai Sitapara",
    whatsapp: "9925258757",
    village: "Tikar ",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Tiles Terding   Zeelsun Ceramic ",
    businessType: "Ceramic  Terding ",
    email: "Manojsitapara06@Gmail.com",
    website: "",
    address: "Zeelsun Ceramic  ,Shubh Complex  Mhendarnagar chokadi",
    visitingCard: ""
  },
  {
    fullName: "Sanghani rakesh ganeshbhai",
    whatsapp: "9727133592",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "Luck. Fashion and. Tailor",
    businessType: "Cloth. Sutting shirting and  redimet",
    email: "Rakeshpatel9211@gemail.com",
    website: "",
    address: "Dr.takhtshihji rod  parmanik show room ni bajuma. Bhagvat complex",
    visitingCard: ""
  },
  {
    fullName: "Fultariya Ratilal bachu bhai",
    whatsapp: "9825583912",
    village: "Pratapgarh",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Packaging Shivautopack",
    businessType: "Corrugated Box",
    email: "shivautopack@gmail.com",
    website: "",
    address: "Survey no 109 P5 Tample street Jambudiya",
    visitingCard: ""
  },
  {
    fullName: "Hareshbhai varmora",
    whatsapp: "9979942123",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Gurukru Waterjet tiles cutting ",
    businessType: "Customized Tiles design ",
    email: "",
    website: "",
    address: "",
    visitingCard: ""
  },
  {
    fullName: "METHANIYA DHIMANTBHAI AMRUTLAL",
    whatsapp: "9825467854",
    village: "SAJJANPUR",
    taluka: "Dhrangdhra",
    bloodGroup: "",
    businessName: "SAVIO CERAMICA PVT LTD",
    businessType: "CERAMIC TILES",
    email: "Dapatel67854@gmail.com",
    website: "",
    address: "8 A NATIONAL HIGHWAY",
    visitingCard: ""
  },
  {
    fullName: "Patel Dharmendrabhai Chunibhai",
    whatsapp: "9913672799",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Brilliant School Charadva",
    businessType: "Educational institute ",
    email: "dharmendrapatel269@gmail.com",
    website: "",
    address: "At. Charadva Ta. Halvad",
    visitingCard: ""
  },
  {
    fullName: "Sanghani ashvinbhai ganeshbhai ",
    whatsapp: "9979451840",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Guru emporium & tailor",
    businessType: "Sutting &shirtting ",
    email: "aptelp 86@gmai.com",
    website: "",
    address: "Jalaram complex,dr.takhtshinghji road, Khoja Khana sheri, morbi",
    visitingCard: ""
  },
  {
    fullName: "Mahesh bhai Avchar Bhai Patel",
    whatsapp: "9924860008",
    village: "Ajitgadh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Ma Roadlines",
    businessType: "Transport",
    email: "maheshgothi006@gmail.com",
    website: "",
    address: "Mahendra nagar Chokdi, Hariom park, Morbi.",
    visitingCard: "https://drive.google.com/open?id=1BdfMYi_9hxrZCxg-q7fiGpmr96RCkXDK, https://drive.google.com/open?id=1sZExv3IIwEv0_uixh3sPYxX5CZXwozbj"
  },
  {
    fullName: "Khavdiya Hasmukhbhai babubhai ",
    whatsapp: "9426449802",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Shree ram power control",
    businessType: "All led product manufacturer, office light, factory light, home light, all outdoor lighting, & all type electric item",
    email: "srpc21@yahoo.com",
    website: "",
    address: "1-LATI PLOT NEAR: KRISHNA HOSPITAL",
    visitingCard: ""
  },
  {
    fullName: "Gadhiya sunil",
    whatsapp: "9925001510",
    village: "Juna Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Uma cab",
    businessType: "Uma cab ",
    email: "Sunilpatel25895@gmail.com",
    website: "",
    address: "Mahendranagar chokdi, near cng pump",
    visitingCard: "https://drive.google.com/open?id=1pDX-HrG4hECCoRAYM53sgeLKtHHK6R8S"
  },
  {
    fullName: "Zalariya Jignesh Jayantilal ",
    whatsapp: "9978802177",
    village: "Ranekpar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "ASTIS CERAMIC LLP",
    businessType: "Ceramic Tiles",
    email: "Jignesh.astaceramic@gmail.com",
    website: "",
    address: "Khokhada Hanuman Road Bela (Rangpar)",
    visitingCard: "https://drive.google.com/open?id=1dn8xvoCB1-Uiu2wPSOK4t2sna8UKJSsv"
  },
  {
    fullName: "AGOLA KAMLESHBHAI SUNDARJIBHAI ",
    whatsapp: "8000039794",
    village: "Navi Kidi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "DAVANTI INTERNATIONAL PVT. LTD. ",
    businessType: "Trading",
    email: "davantiinternational@gmail.com",
    website: "",
    address: "Shop. No.5, Swagat Chamber, Near Swagat Ceramic, Old Ghuntu Road, Morbi-Halvad. ",
    visitingCard: "https://drive.google.com/open?id=1lCrR74TsCMS0MGaqk4kFs4fpmwpKv7-G"
  },
  {
    fullName: "Patel Mahendra Thobhan bhai (Bhut)",
    whatsapp: "7046230772",
    village: "Dharmendragadh",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Bahuchar polymer ",
    businessType: "Pp genual ",
    email: "Amitzalariya5799@gmail.com",
    website: "Bahuchar polymer ",
    address: "Lajai",
    visitingCard: "https://drive.google.com/open?id=1jOSCi5VZGBlWz0n2UgzZckrnoG6UEoBd"
  },
  {
    fullName: "Ashvinbhai rachhadiya",
    whatsapp: "9913564339",
    village: "Katoda",
    taluka: "Wadhwan",
    bloodGroup: "O+",
    businessName: "Rudra tools hardware",
    businessType: "Hardware",
    email: "Ashvin712@",
    website: "",
    address: "Galaxy plaza, umiya circle, shanala road",
    visitingCard: "https://drive.google.com/open?id=1w4KMkQl2eVe8KfgvYFibugPkBhUoCHzd"
  },
  {
    fullName: "Dr. Punita Hiren Sanghani",
    whatsapp: "9737223555",
    village: "Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Aarav Dental Studio ",
    businessType: "Dental clinic ",
    email: "dr.punitapatel@gmail.com",
    website: "",
    address: "Aarav Dental Studio, 32,33 Third floor, Capital Market, Ravapar Chokadi, Morbi 363641",
    visitingCard: ""
  },
  {
    fullName: "Malvaniya Janak bhai shankar Bhai ",
    whatsapp: "9638705480",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Bahuchar polymer ",
    businessType: "Pp granual",
    email: "Amitzalriya5799@gmail.com",
    website: "Bahuchar polymer ",
    address: "Lajai",
    visitingCard: "https://drive.google.com/open?id=191ETWi0C_3WfE5PYUIFKScNZLT8Elqr0"
  },
  {
    fullName: "JAY PATEL",
    whatsapp: "9687757000",
    village: "Surendranagar",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "HINDGRES CERAMICA PVT LTD",
    businessType: "CERAMIC TILE MANUFACTURERS ",
    email: "Jay@hindgres.com",
    website: "Hindgres.com",
    address: "Survey no 115p makansar 8a national highway morbi gujrat 363641",
    visitingCard: ""
  },
  {
    fullName: "Zalariya Rashminbhai Jayantilal",
    whatsapp: "9898447877",
    village: "Ranekpar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Asta ceramic pvt ltd",
    businessType: "Manufacturing of parking tiles",
    email: "dr.rjpatel1312@gmail.com",
    website: "",
    address: "Asta ceramic pvt ltd, opp-bela village pipali road morbi",
    visitingCard: ""
  },
  {
    fullName: "Sanghani Dhaval Natvarlal",
    whatsapp: "9099609176",
    village: "Danawada",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Aashvi Enterprise ",
    businessType: "Ceramic machinery spare parts.",
    email: "aashvienterprise05@gmail.com",
    website: "",
    address: "Real plaza,near vardhman hotel shop no.17",
    visitingCard: ""
  },
  {
    fullName: "Haresh bhai mansukh bhai Varmora",
    whatsapp: "9712345366",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "O+",
    businessName: "Harikrishna mojek",
    businessType: "Mojek Tiles Manufacturer",
    email: "hareshpatel5854@gmail.com",
    website: "",
    address: "Pipali Road, Behind Lords Hotel, Morbi.",
    visitingCard: "https://drive.google.com/open?id=15N-GGXSA40AbNjX7RMXkQURAYEu4eA_t"
  },
  {
    fullName: "Dhoriyani Jalpeshbhai Harjivanbhai",
    whatsapp: "7069888401",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Henshi Motor Rewinding",
    businessType: "Motor Revinding",
    email: "jalpeshpatel2411@gmail.com",
    website: "",
    address: "Matel road",
    visitingCard: ""
  },
  {
    fullName: "Labkamana pareshbhai kanjibhai",
    whatsapp: "7819895195",
    village: "Thala",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Aryan marketing",
    businessType: "Tiles showroom retail and Holsell",
    email: "labkamanaparesh4332@gmail.com",
    website: "www.aryanmarketing.com",
    address: "Marketing tiles",
    visitingCard: "https://drive.google.com/open?id=1_LLSn2rfCp16gpUS84Kw-fgbCQ2TDusB"
  },
  {
    fullName: "Motka Rajesh bhai dayaljibhai ",
    whatsapp: "9727632256",
    village: "Mota Ankevaliya",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "SAHAJANAND ELECTRIC STORE ",
    businessType: "Electric penal",
    email: "rajupatel32256@gmail.com",
    website: "",
    address: "8A NATIONAL HIGHWAY LALAPAR ",
    visitingCard: "https://drive.google.com/open?id=1Ne3R05qs73FiwNTQvWyxDm9yf6EWveRn"
  },
  {
    fullName: "labkamana pareshbhai kanjibhai",
    whatsapp: "7819895195",
    village: "Thala",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Aryan marketing",
    businessType: "Tiles showroom retail",
    email: "labkamanaparesh4332@gmail.com",
    website: "",
    address: "",
    visitingCard: "https://drive.google.com/open?id=1jNTCAxmi-kshKCuc2M_8eG-DdS2PwBSH"
  },
  {
    fullName: "MAYUR PRANBHAI PARJIYA",
    whatsapp: "8140526865",
    village: "RANMALPUR",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "SARVOPARI IMPEX",
    businessType: "Export wooden pallets and packing ",
    email: "Sarvopariimpex@gmail.com",
    website: "www.sarvopariimpex.com",
    address: "Plot no 1 survey number 164 pipli village jetpar road morbi",
    visitingCard: ""
  },
  {
    fullName: "Barasara arvind nagji bhai",
    whatsapp: "9909541039",
    village: "Dharmendragadh",
    taluka: "Muli",
    bloodGroup: "B+",
    businessName: "Nachiketa mashala ",
    businessType: "Food business ",
    email: "barasraarvind8 3@gmail.com",
    website: "",
    address: "Sanala rod , G.I.D.C. , K1-48 , ",
    visitingCard: "https://drive.google.com/open?id=1Em-obTFXvQxy86I-DGqDw1Uj4PyjNif3"
  },
  {
    fullName: "Motka Harshkumar Vasudevbhai ",
    whatsapp: "9173336069",
    village: "Mota Ankevaliya",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "BLOFLEX SURGICAL INDUSTRIES",
    businessType: "Syringe manufacturers ",
    email: "bloflexsurgicalind@gmail.com",
    website: "www.bloflex.in",
    address: "Halvad ",
    visitingCard: "https://drive.google.com/open?id=1HFa46wKPxBTx6eC9tr0jRidUCFNOYpIv"
  },
  {
    fullName: "SANTOKI KAUSHIKKUMAR CHAMANBHAI",
    whatsapp: "9726465945",
    village: "Gujarvadi",
    taluka: "Dhrangdhra",
    bloodGroup: "O-",
    businessName: "ELVISH INDUSTRIES ",
    businessType: "HAND MADE KITCHEN SINK",
    email: "Kaushik0096@gmail.com",
    website: "www.elvishindustries.com",
    address: "Plot. No . 24/25 ,b/h vishal furniture, near ambica engineering ",
    visitingCard: "https://drive.google.com/open?id=1z1Kc4s01csCQiS1_FISsUHIQABKH5H5r"
  },
  {
    fullName: "Vamja karsan bhai ",
    whatsapp: "9724359471",
    village: "Ranmalpur",
    taluka: "Halvad",
    bloodGroup: "O-",
    businessName: "Santkrupa enterprise and tiles cutting ",
    businessType: "Treding tiles ",
    email: "dkvamja@gmail.com",
    website: "",
    address: "Halvad road uma residanshi ni bajuma",
    visitingCard: ""
  },
  {
    fullName: "Parejiya Nilesh Bhikhalal ",
    whatsapp: "9265800719",
    village: "Dudhrej",
    taluka: "Wadhwan",
    bloodGroup: "A+",
    businessName: "Oculus Impex ",
    businessType: "Flooring carpet treding ",
    email: "oculusimpex@gmail.com",
    website: "www.oculusimpex.com",
    address: "Pipli road, Morbi",
    visitingCard: "https://drive.google.com/open?id=1EYe0Uavyd-nEAbD-DhMOzdpK78R3uJn4"
  },
  {
    fullName: "Padsumbiya Dilip bhai Prabhu Bhai ",
    whatsapp: "9913557075",
    village: "Ishwarnagar",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "SHIV CERA CERAMIC ",
    businessType: "Tiles trending ",
    email: "dilip.qubictiles@gmail.com",
    website: "",
    address: "Kaka chembar Shop -9 B/h vishal furniture ",
    visitingCard: ""
  },
  {
    fullName: "Aghara Pravin Bhai Shivlal bhai",
    whatsapp: "9879456366",
    village: "Ishwarnagar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Kishan Computer",
    businessType: "Accountant",
    email: "infokishancom@gmail.com",
    website: "",
    address: "Ilora shoping, Behind Hotel Manali, Opp. New Bus Stand, Sanala Road, Morbi.",
    visitingCard: "https://drive.google.com/open?id=1TMA6H_yGSmGEV_zlvT4JLH3-HSpDbHbI"
  },
  {
    fullName: "Gadhiya Mansi Kamleshbhai",
    whatsapp: "8140024382",
    village: "Dhulkot",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Gadhiya interior design studio ",
    businessType: "All Types Of Interior Design ",
    email: "gadhiyainterior@gmail.com",
    website: "",
    address: "Gayatri nagar 1 , block no 48 , ravapar road , near umiya chock , morbi",
    visitingCard: "https://drive.google.com/open?id=1x6vEYIvUV-O_fNZOcqzgSyZdRXg7SwsL, https://drive.google.com/open?id=1LsnjmaNjm8jTPL3pTOUDXT5MP64aEOCe"
  },
  {
    fullName: "Surani vijaykumar ratilal",
    whatsapp: "9638916304",
    village: "Survadar",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "IGNITE PAPER",
    businessType: "Manufacturer ",
    email: "ignitepapers2023@gmail.com",
    website: "www.ignitepaper.com",
    address: "Hadmatiya road lajai chokadi",
    visitingCard: "https://drive.google.com/open?id=12_TTnNSmJsNB_Y0hUlYgNj5nMSu_JYTa"
  },
  {
    fullName: "Patel satishbhai tribhovanbhai",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiv electricals and rewinding",
    businessType: "Make arc welding machine",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Opposite ramdhan aashram shop no. 11 mahendra nager road, morbi 2",
    visitingCard: ""
  },
  {
    fullName: "Patel satishbhai tribhovanbhai ",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiva electricals and rewinding",
    businessType: "Make arc welding machine",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Oppo. Ramdhan aashram shop no. 11,morbi2 mahendra nagar road",
    visitingCard: ""
  },
  {
    fullName: "Hulani Anil Bhai baldev Bhai ",
    whatsapp: "9913758097",
    village: "Mangadh",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Harikrishna febrikesan",
    businessType: "Harikrishna febrikesan ",
    email: "",
    website: "",
    address: "Mahendra nagar",
    visitingCard: ""
  },
  {
    fullName: " Patel satishbhai tribhovanbhai",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiv electricals and rewinding ",
    businessType: "Make arc welding machine ",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Opposite ramdhan aashram,morbi 2,shop no.2,mahendra nagar road",
    visitingCard: ""
  },
  {
    fullName: "Patel satishbhai tribhovanbhai ",
    whatsapp: "9726529905",
    village: "dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiv electricals and rewinding ",
    businessType: "Make arc welding machine ",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Opposite ramdhan aashram morbi 2 shop no.11, mahendra nagar road ",
    visitingCard: ""
  },
  {
    fullName: "Varmora Divyang Vallabhbhai",
    whatsapp: "9825797977",
    village: "Sara",
    taluka: "Muli",
    bloodGroup: "A+",
    businessName: "Shree Royal Polyplast Industries",
    businessType: "Manufacturing ",
    email: "divyang.varmora@yahoo.com",
    website: "www.royalpolyplast.com",
    address: "Morbi - Navlakhi Highway, Pipaliya Char Rasta,",
    visitingCard: ""
  },
  {
    fullName: "GOTHI JITENDRABHAI SAVJIBHAI ",
    whatsapp: "9879329266",
    village: "AJITGADH ",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "HARIOM CERAMIC",
    businessType: "CERAMIC TILES TRADING ",
    email: "hariomceramic@gmail.com",
    website: "",
    address: "FIRST FLOOR,  OFFICE NO. 16, TULSHI CHAMBERS, OLD GHUNTU ROAD, TRAJPAR CROSS ROAD, MORBI-363642 (GUJARAT) INDIA ",
    visitingCard: ""
  },
  {
    fullName: "Pravin bhai moradiya",
    whatsapp: "9925726346",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Lucian ceramic ",
    businessType: "Ceramic tiles ",
    email: "moradiyapravin954@gmail.com",
    website: "Lucian ceramic ",
    address: "Yogesh potri,old ghutu road, morbi-2",
    visitingCard: ""
  },
  {
    fullName: "DESAI SURESHBHAI GANDUBHAI",
    whatsapp: "9925675554",
    village: "Survadar",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "SHRI JI ALUMINIUM SHOP",
    businessType: "DOOR MAKING",
    email: "sd4639767@gmail.com",
    website: "",
    address: "MAHENDRANAGAR-- NEAR KRANTIJYOT PARK -- SUPER MARKET 2 - SHOP NUMBER 6",
    visitingCard: ""
  },
  {
    fullName: "Patel satishbhai tribhovanbhai ",
    whatsapp: "9726529905",
    village: "Dhrangadhra",
    taluka: "Dhrangdhra",
    bloodGroup: "AB+",
    businessName: "Shiv electricals and rewinding ",
    businessType: "Make arc welding machine ",
    email: "sp8857206@gmail.com",
    website: "",
    address: "Opposite ramdhan aashram, shop no.11, morbi 2 mahendranagar road",
    visitingCard: "https://drive.google.com/open?id=1ewonqdRQG_KDxUznvM0DZvjLMa4vCMtS"
  },
  {
    fullName: "Dethariya Harshad Jethabhai ",
    whatsapp: "9099241436",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Dethariya Modular Solution ",
    businessType: "Modular Kitchen ",
    email: "hjdethariya888@gmail.com",
    website: "",
    address: "K-1/77 GIDC, Sanala Road, Near Krishna Bakery, Morbi",
    visitingCard: "https://drive.google.com/open?id=1oUnFcth7uz8S0ikBU6mjKxaQf2Lgze9B"
  },
  {
    fullName: "KHAVADEEYA CHETANKUMAR RATANSHIBHAI",
    whatsapp: "8469067870",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "GRINDELWALD CORPORATION",
    businessType: "Plastic Corner Manufacturer",
    email: "grindelwaldcorporation@gmail.com",
    website: "",
    address: "Bhadiyad. Morbi, Gujarat, India.",
    visitingCard: "https://drive.google.com/open?id=1PHsN1qQQOarh_HDbFupD_W0-jwsj840A"
  },
  {
    fullName: "Keraliya Nirav Bhagvatbhai ",
    whatsapp: "9979375602",
    village: "Mahendrnagar",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Thakardhani refrigerator ",
    businessType: "Freez Service and repairing ",
    email: "Nbkeraliya056@gmail.com",
    website: "",
    address: "Mahendrnagar ghutu road, shyam park same, shivshakti complex-1, shop no. 10",
    visitingCard: "https://drive.google.com/open?id=1fulZqgXldi6RP5QXSqPqmHxZO3oT1SKC"
  },
  {
    fullName: "Kaila Pruthvik Dipakbhai",
    whatsapp: "7818851505",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "AB-",
    businessName: "supraanti india",
    businessType: "Education, Import-Export, Digital Marketing ",
    email: "supraanti.export@gmail.com",
    website: "https://supraantiindia.com/",
    address: "4th Floor, Above Sanket India, Umiya Circle, Sanala Road, Morbi - 363641, Gujarat, India",
    visitingCard: ""
  },
  {
    fullName: "Vadhrodiya Rajesh Mansukhbhai",
    whatsapp: "9724570138",
    village: "Halvad",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Sitara Microns",
    businessType: "All Types Of Ceramic Row Material",
    email: "sitaramicrons@gmail.com",
    website: "",
    address: "Opp. Uhchi Mandal, Nr. Marbilano Surface,Talavaiya Sanala Road, Morbi-363641",
    visitingCard: "https://drive.google.com/open?id=1mDje2WX8FstXilMlY7GxMmeeXkAHLrl1"
  },
  {
    fullName: "AGHARA HITESHBHAI RAMJIBHAI",
    whatsapp: "9898235577",
    village: "Juna Devaliya",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "PATIDAR ENTERPRISE",
    businessType: "Trading Of 3M Scotchbrites for Sanitarywares, Wide Sanding Belts for Laminates and Others finsihing products.",
    email: "PATIDARENTERPRISE23@GMAIL.COM",
    website: "",
    address: "OFFICE-A, LALPAR INDUSTRIAL ESTATE - 1, PLOT NO.14, 8-A, N.H., LALPAR, MORBI-363642.",
    visitingCard: "https://drive.google.com/open?id=1iPdXtt08e_guJGoU5-EFjG_s3tMsk67S"
  },
  {
    fullName: "UGHAREJA PRAHLADBHAI AMRUTBHAI ",
    whatsapp: "7041212121",
    village: "Vaghgadh ",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "Shivam multispecility Hospital,  Morbi 2",
    businessType: "Orthopedic surgeon ",
    email: "drprahladughareja@gmail.com",
    website: "",
    address: "Shivam Multispecialty hospital Mahendranagar Road Morbi - 2",
    visitingCard: "https://drive.google.com/open?id=1cXetCDNhsE17mP_1qxmp9ByxsZLhSued, https://drive.google.com/open?id=1TYvGV591HDpwGrSL0BAg1VWxZwJpHuqz"
  },
  {
    fullName: "Aervadiya Chiragbhai Rajeshbhai",
    whatsapp: "9638834394",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "AB+",
    businessName: "Holo Sanitaryware Pvt Ltd ",
    businessType: "Manufacturing of Sanitaryware Products ",
    email: "",
    website: "https://holosanitaryware.com/",
    address: "Survey No.723 P3, 724 1 PAIKI 1, 724 1 PAIKI 2, Old Ghuntu Rd, near Evernew paper mill, Lakhdhirpur, Morbi, Ghuntu, Gujarat 363642",
    visitingCard: "https://drive.google.com/open?id=1-43T5HlzAvYfiV46EsCC_zBIu0hZ1YCr"
  },
  {
    fullName: "Dethariya kishan Mansukhbhai ",
    whatsapp: "8306039418",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B-",
    businessName: "Bhagvati clinic ",
    businessType: "Doctor ",
    email: "1234kishandethariya@gmail.com",
    website: "",
    address: "Bhagvati clinic,dhuva chokdi, matel road morbi ",
    visitingCard: "https://drive.google.com/open?id=1rdvyiTFzkyzsy3QhCw-SHwZ8R1EW_5V9"
  },
  {
    fullName: "Arvadiya Dhawal bhai Raghavji bhai",
    whatsapp: "9825802100",
    village: "N/A",
    taluka: "N/A",
    bloodGroup: "B-",
    businessName: "Jay Muralidhar Travels ",
    businessType: "Tours & Travels ",
    email: "Dhawalpatel13215@gmail.com",
    website: "",
    address: "6-7 Lati Plot Main Road Morbi",
    visitingCard: ""
  },
  {
    fullName: "Gopani Lalitbhai Savjibhai",
    whatsapp: "9725280500",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "",
    businessName: "Maruti Motors",
    businessType: "Car repair",
    email: "prayaggopani28@gmail.com",
    website: "",
    address: "Behind Limda vala meldi mataji temple, Morbi - Rajkot Highway, Shakti Sanala, Morbi.",
    visitingCard: ""
  },
  {
    fullName: "MORADIYA ASHOK BHAI RAMJI BHAI ",
    whatsapp: "9979070805",
    village: "VANKIYA",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "KISHAN ENGINEERING WORKS ",
    businessType: "WORKSHOP (M D M E)",
    email: "ashokrmoradiya@gmail.com",
    website: "",
    address: "8-A N.H. NEAR G.K. HOTEL TRAJPAR CHOKDI MORBI -2",
    visitingCard: "https://drive.google.com/open?id=1u3YI2aFGtcIWhdeqvyUuQbfamXyVQc1o, https://drive.google.com/open?id=1DZrmfsvBD7i_bjGfcG06fvOFjohSqJzj"
  },
  {
    fullName: "Jayesh m patel ",
    whatsapp: "9924833860",
    village: "LIMBADI",
    taluka: "LIMBADI",
    bloodGroup: "AB+",
    businessName: "Khodiyar auto garege",
    businessType: "Bike survice &repering",
    email: "Pateljayesh99248@gmail.com",
    website: "",
    address: "Super market 2 behind  mahendranagar busstand shop no16",
    visitingCard: ""
  },
  {
    fullName: "Araniya jitendar bhai narayan bhai",
    whatsapp: "9537899321",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Moment technology",
    businessType: "CCTV CAMERA ALL",
    email: "areniyajitendar@gmail.com",
    website: "",
    address: "Mhedarnagar morbi 2",
    visitingCard: "https://drive.google.com/open?id=1KhYdWrRhqogG3Q1Fv3MGXMODG2IfStfo"
  },
  {
    fullName: "JAKASANIYA HARDIKKUMAR GIRDHARLAL",
    whatsapp: "8140162624",
    village: "RAJCHARADI",
    taluka: "Dhrangdhra",
    bloodGroup: "B+",
    businessName: "EXCELLENT CONSULTANCY",
    businessType: "GST CONSULTANCT AND TAX ADVISER",
    email: "EXCELLENTMORBI@GMAIL.COM",
    website: "",
    address: "S-19, SUPER MARKET-2, NEAR KRANTIKJYOT PARK, OPP. PRABHUKRUPA TOWNSHIP, MAHENDRANAGAR, MORBI",
    visitingCard: "https://drive.google.com/open?id=169wo-zuVvH5jceMESaQv9Dn5_qJ0-KVL, https://drive.google.com/open?id=1rLCw8dxUBqiPuIOGaBFWB5f8I5fkBDNk"
  },
  {
    fullName: "Butani sachinhareshbhai",
    whatsapp: "7069506626",
    village: "Khajeli",
    taluka: "Wadhwan",
    bloodGroup: "B+",
    businessName: "Auralam laminates llp",
    businessType: "Manufacturing ",
    email: "sbutani04@gmail.com",
    website: "Auralamlaminates.com",
    address: "Survey no. 164/5,opp. Sarvoday hotel, NH - 8A, juna sadulka, morbi, Gujarat(India).",
    visitingCard: "https://drive.google.com/open?id=1R3ZGbte9LtrUQAIfoG4DQD4whMFl6n07"
  },
  {
    fullName: "CHHANIYARA MANOJ CHANDUBHAI",
    whatsapp: "9979911100",
    village: "Nava Ghanshyamgadh",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "MILLION CERAMIC",
    businessType: "CERAMIC WALL TILES",
    email: "manojpatel161187@gmail.com",
    website: "",
    address: "8-a, National highway, At-DHUVA, ",
    visitingCard: "https://drive.google.com/open?id=1UWwtmUVnqI8ktvwo3JYccuZmDsDsYfJg, https://drive.google.com/open?id=1sJj_m9-kGX4RYy5dGm5HA4OEsoVDrQ0Q"
  },
  {
    fullName: "Dalsaniya Preet DhanjiBhai ",
    whatsapp: "6356321115",
    village: "N/A",
    taluka: "N/A",
    bloodGroup: "",
    businessName: "ORYN MINCHEM ",
    businessType: "Bopp Tape ",
    email: "preetdalsaniya2046@gmail.com",
    website: "",
    address: "Morbi",
    visitingCard: ""
  },
  {
    fullName: "ARVADIYA HIREN LALITBHAI",
    whatsapp: "9277404603",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "PAVAN COMPUTER",
    businessType: "ALL TYPE OF COMPUTER JOBWORK, ELECTION CARD NEW,  ELECTION CARD CORRECTION,  DRIVING LICENCE NEW, DRIVING LICENCE RENEW, PASSPORT, ALL TYPE OF COMPUTER JOB WORK AND RTO WORK",
    email: "pavancomputer4603@gmail.com",
    website: "",
    address: "PAVAN COMPUTER, GOLDEN POINT, FIRST FLOOR, NEAR HIGH WAY JAKAT NAKA, JINPARA, WANKANER",
    visitingCard: "https://drive.google.com/open?id=10vNIqGw17I7socW2prMymwJ7ogs5Hjdc"
  },
  {
    fullName: "Khavadeeya kaushik pravinbhai",
    whatsapp: "9638103777",
    village: "Ratabher",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Maamantchemico LLP",
    businessType: "Pvc and plastic additives and speciality chemical, Also paint and rubber additives.",
    email: "info@maamantra.com",
    website: "Www.maamantra.com",
    address: "Plot 107, Shreeji estate, Sanala byepass, Morbi-363641.",
    visitingCard: "https://drive.google.com/open?id=1yY-wVo-VsssPeBisZfsXBLOvALyBNsaS"
  },
  {
    fullName: "Bhoraniya Hiteshbhai Dayabhai",
    whatsapp: "9978102862",
    village: "Morbi",
    taluka: "Halvad",
    bloodGroup: "B+",
    businessName: "Krishna engineering and Mechanical",
    businessType: "Piston air compressor sels and services & all type of water pump services & gear box services",
    email: "krishanaeng789@gmail.com",
    website: ". ",
    address: "Old ghutu road, near yogesh potry, morbi 2",
    visitingCard: "https://drive.google.com/open?id=14fM8d9uucylnTjZtapYROTUmQm6UAFaq"
  },
  {
    fullName: "ASHOKBHAI Ramjibhai MORDIYA ",
    whatsapp: "9979070805",
    village: "Vakiya ",
    taluka: "Halvad",
    bloodGroup: "A+",
    businessName: "Kishan engineering works ",
    businessType: "Workshop",
    email: "Ashokrmordiya@gmail.com",
    website: "",
    address: "Tajpar chokadi near g k hotel 8-a national highway,morbi ",
    visitingCard: ""
  },
  {
    fullName: "Vishal motka ",
    whatsapp: "8866590300",
    village: "Manpur",
    taluka: "Dhrangdhra",
    bloodGroup: "O+",
    businessName: "Airson plaster product& Airson packaging ",
    businessType: "Plot no 5,om industrial estate near khokhara hanuman temple bela ",
    email: "Vishal.motka@gmail.com ",
    website: "",
    address: "",
    visitingCard: "https://drive.google.com/open?id=1DEDuEsAQuI-LEUXDj1RUPkUQMpfoVICK"
  },
  {
    fullName: "Arvinbhai rachadiya ",
    whatsapp: "9913580741",
    village: "Katuda",
    taluka: "Wadhwan",
    bloodGroup: "O+",
    businessName: "Rudra power tools & hardware ",
    businessType: "Personal ",
    email: "",
    website: "",
    address: "Galaxy plaza umiya circle sanala road ,morbi ",
    visitingCard: "https://drive.google.com/open?id=13mi4HR7_F4sS8zDJhmFYUNgAbXjuWoOH"
  },
  {
    fullName: "Arvadiya Raviraj Sanjaykumar ",
    whatsapp: "7990688364",
    village: "Tikar",
    taluka: "Halvad",
    bloodGroup: "O+",
    businessName: "Jagdamba Construction ",
    businessType: "Personal Business ",
    email: "hitech.planing@gmail.com",
    website: "",
    address: "Laxmi plaza, second floor,shop no 3, sanala road, Morbi ",
    visitingCard: "https://drive.google.com/open?id=1XQE_FG_Vv04nLxzqYNIBEhUaTqQJdTQh"
  }
];
